[2024-09-19 12:10:24,870][numexpr.utils][INFO] - NumExpr defaulting to 8 threads.
[2024-09-19 12:10:27,566][flwr][WARNING] - Both server and strategy were provided, ignoring strategy
[2024-09-19 12:10:27,567][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-19 12:10:35,969][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'node:127.0.0.1': 1.0, 'CPU': 8.0, 'object_store_memory': 587023564.0, 'memory': 1174047131.0}
[2024-09-19 12:10:35,971][flwr][INFO] - Initializing global parameters
[2024-09-19 12:10:35,972][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-19 12:10:39,402][flwr][INFO] - Received initial parameters from one random client
[2024-09-19 12:10:39,407][flwr][INFO] - Evaluating initial parameters
[2024-09-19 12:10:39,449][flwr][INFO] - initial parameters (loss, other metrics): 16.634782600402833, {'global accuracy': 0.43833333333333335}
[2024-09-19 12:10:39,450][flwr][INFO] - FL starting
[2024-09-19 12:10:39,452][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-19 12:10:39,500][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=11080, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\VscodeProjects\Tesi-Francesco\clients\client_scaffold.py", line 56, in fit
    if os.path.exists(f"{self.dir}/client_cv_{self.cid}.pt"):
                                              ^^^^^^^^
AttributeError: 'ScaffoldFlowerClient' object has no attribute 'cid'
[2024-09-19 12:10:43,082][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=10000, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\VscodeProjects\Tesi-Francesco\clients\client_scaffold.py", line 56, in fit
    if os.path.exists(f"{self.dir}/client_cv_{self.cid}.pt"):
                                              ^^^^^^^^
AttributeError: 'ScaffoldFlowerClient' object has no attribute 'cid'
[2024-09-19 12:10:43,090][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
