[2024-09-26 15:46:28,879][flwr][WARNING] - Both server and strategy were provided, ignoring strategy
[2024-09-26 15:46:28,879][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=100, round_timeout=None)
[2024-09-26 15:46:39,621][flwr][INFO] - Flower VCE: Ray initialized with resources: {'object_store_memory': 655930982.0, 'memory': 1311861966.0, 'CPU': 12.0, 'node:__internal_head__': 1.0, 'node:127.0.0.1': 1.0}
[2024-09-26 15:46:39,622][flwr][INFO] - Initializing global parameters
[2024-09-26 15:46:39,622][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-26 15:46:44,102][flwr][INFO] - Received initial parameters from one random client
[2024-09-26 15:46:44,103][flwr][INFO] - Evaluating initial parameters
[2024-09-26 15:46:44,164][flwr][INFO] - initial parameters (loss, other metrics): 0.005904449290699429, {'accuracy': 0.44, 'f1-score': 0.005917159763313609}
[2024-09-26 15:46:44,164][flwr][INFO] - FL starting
[2024-09-26 15:46:44,166][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 100)
[2024-09-26 15:46:44,204][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:51,965][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:51,966][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
[2024-09-26 15:46:52,012][flwr][INFO] - fit progress: (1, 0.005904449290699429, {'accuracy': 0.44, 'f1-score': 0.005917159763313609}, 7.8466994000045815)
[2024-09-26 15:46:52,012][flwr][INFO] - evaluate_round 1: no clients selected, cancel
[2024-09-26 15:46:52,012][flwr][DEBUG] - fit_round 2: strategy sampled 2 clients (out of 100)
[2024-09-26 15:46:52,041][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:52,043][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:52,049][flwr][DEBUG] - fit_round 2 received 0 results and 2 failures
[2024-09-26 15:46:52,094][flwr][INFO] - fit progress: (2, 0.005904449290699429, {'accuracy': 0.44, 'f1-score': 0.005917159763313609}, 7.930897400001413)
[2024-09-26 15:46:52,097][flwr][INFO] - evaluate_round 2: no clients selected, cancel
[2024-09-26 15:46:52,097][flwr][DEBUG] - fit_round 3: strategy sampled 2 clients (out of 100)
[2024-09-26 15:46:52,122][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:52,127][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:52,127][flwr][DEBUG] - fit_round 3 received 0 results and 2 failures
[2024-09-26 15:46:52,177][flwr][INFO] - fit progress: (3, 0.005904449290699429, {'accuracy': 0.44, 'f1-score': 0.005917159763313609}, 8.011666799997329)
[2024-09-26 15:46:52,177][flwr][INFO] - evaluate_round 3: no clients selected, cancel
[2024-09-26 15:46:52,177][flwr][DEBUG] - fit_round 4: strategy sampled 2 clients (out of 100)
[2024-09-26 15:46:52,201][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:52,207][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:52,211][flwr][DEBUG] - fit_round 4 received 0 results and 2 failures
[2024-09-26 15:46:52,251][flwr][INFO] - fit progress: (4, 0.005904449290699429, {'accuracy': 0.44, 'f1-score': 0.005917159763313609}, 8.088771700000507)
[2024-09-26 15:46:52,251][flwr][INFO] - evaluate_round 4: no clients selected, cancel
[2024-09-26 15:46:52,251][flwr][DEBUG] - fit_round 5: strategy sampled 2 clients (out of 100)
[2024-09-26 15:46:52,285][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:52,285][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:46:52,288][flwr][DEBUG] - fit_round 5 received 0 results and 2 failures
[2024-09-26 15:46:52,332][flwr][INFO] - fit progress: (5, 0.005904449290699429, {'accuracy': 0.44, 'f1-score': 0.005917159763313609}, 8.170294800002011)
[2024-09-26 15:46:52,332][flwr][INFO] - evaluate_round 5: no clients selected, cancel
[2024-09-26 15:46:52,332][flwr][DEBUG] - fit_round 6: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:00,957][flwr][DEBUG] - fit_round 6 received 2 results and 0 failures
[2024-09-26 15:47:01,003][flwr][INFO] - fit progress: (6, 0.005902331670125325, {'accuracy': 0.43944444444444447, 'f1-score': 0.003948667324777887}, 16.84187249999377)
[2024-09-26 15:47:01,003][flwr][INFO] - evaluate_round 6: no clients selected, cancel
[2024-09-26 15:47:01,003][flwr][DEBUG] - fit_round 7: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:08,416][flwr][DEBUG] - fit_round 7 received 2 results and 0 failures
[2024-09-26 15:47:08,456][flwr][INFO] - fit progress: (7, 0.005886096921232011, {'accuracy': 0.4411111111111111, 'f1-score': 0.01949317738791423}, 24.291923099997803)
[2024-09-26 15:47:08,456][flwr][INFO] - evaluate_round 7: no clients selected, cancel
[2024-09-26 15:47:08,456][flwr][DEBUG] - fit_round 8: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:08,487][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:14,826][flwr][DEBUG] - fit_round 8 received 1 results and 1 failures
[2024-09-26 15:47:14,871][flwr][INFO] - fit progress: (8, 0.005884467462698619, {'accuracy': 0.4388888888888889, 'f1-score': 0.00980392156862745}, 30.707378499995684)
[2024-09-26 15:47:14,874][flwr][INFO] - evaluate_round 8: no clients selected, cancel
[2024-09-26 15:47:14,874][flwr][DEBUG] - fit_round 9: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:15,039][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:15,057][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:15,058][flwr][DEBUG] - fit_round 9 received 0 results and 2 failures
[2024-09-26 15:47:15,105][flwr][INFO] - fit progress: (9, 0.005884467462698619, {'accuracy': 0.4388888888888889, 'f1-score': 0.00980392156862745}, 30.939617900003213)
[2024-09-26 15:47:15,105][flwr][INFO] - evaluate_round 9: no clients selected, cancel
[2024-09-26 15:47:15,107][flwr][DEBUG] - fit_round 10: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:15,132][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:15,355][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:15,366][flwr][DEBUG] - fit_round 10 received 0 results and 2 failures
[2024-09-26 15:47:15,413][flwr][INFO] - fit progress: (10, 0.005884467462698619, {'accuracy': 0.4388888888888889, 'f1-score': 0.00980392156862745}, 31.24753690000216)
[2024-09-26 15:47:15,413][flwr][INFO] - evaluate_round 10: no clients selected, cancel
[2024-09-26 15:47:15,413][flwr][DEBUG] - fit_round 11: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:15,447][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:15,447][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:15,455][flwr][DEBUG] - fit_round 11 received 0 results and 2 failures
[2024-09-26 15:47:15,502][flwr][INFO] - fit progress: (11, 0.005884467462698619, {'accuracy': 0.4388888888888889, 'f1-score': 0.00980392156862745}, 31.336329900004785)
[2024-09-26 15:47:15,502][flwr][INFO] - evaluate_round 11: no clients selected, cancel
[2024-09-26 15:47:15,502][flwr][DEBUG] - fit_round 12: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:15,540][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:22,012][flwr][DEBUG] - fit_round 12 received 1 results and 1 failures
[2024-09-26 15:47:22,059][flwr][INFO] - fit progress: (12, 0.0058777758479118345, {'accuracy': 0.43944444444444447, 'f1-score': 0.013685239491691105}, 37.89994000000297)
[2024-09-26 15:47:22,066][flwr][INFO] - evaluate_round 12: no clients selected, cancel
[2024-09-26 15:47:22,066][flwr][DEBUG] - fit_round 13: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:22,090][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:22,090][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:22,090][flwr][DEBUG] - fit_round 13 received 0 results and 2 failures
[2024-09-26 15:47:22,137][flwr][INFO] - fit progress: (13, 0.0058777758479118345, {'accuracy': 0.43944444444444447, 'f1-score': 0.013685239491691105}, 37.97746809999808)
[2024-09-26 15:47:22,137][flwr][INFO] - evaluate_round 13: no clients selected, cancel
[2024-09-26 15:47:22,137][flwr][DEBUG] - fit_round 14: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:22,174][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:33,571][flwr][DEBUG] - fit_round 14 received 1 results and 1 failures
[2024-09-26 15:47:33,613][flwr][INFO] - fit progress: (14, 0.005861654844548967, {'accuracy': 0.44222222222222224, 'f1-score': 0.045627376425855515}, 49.45182170000044)
[2024-09-26 15:47:33,613][flwr][INFO] - evaluate_round 14: no clients selected, cancel
[2024-09-26 15:47:33,613][flwr][DEBUG] - fit_round 15: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:33,645][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2780, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
[2024-09-26 15:47:40,045][flwr][DEBUG] - fit_round 15 received 1 results and 1 failures
[2024-09-26 15:47:40,098][flwr][INFO] - fit progress: (15, 0.005852107107639313, {'accuracy': 0.44055555555555553, 'f1-score': 0.057998129092609915}, 55.933723199996166)
[2024-09-26 15:47:40,098][flwr][INFO] - evaluate_round 15: no clients selected, cancel
[2024-09-26 15:47:40,098][flwr][DEBUG] - fit_round 16: strategy sampled 2 clients (out of 100)
[2024-09-26 15:47:40,132][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6296, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 116, in client_fn
    trainloader = trainloaders[int(cid)]
                  ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
