[2024-09-12 10:38:34,987][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-12 10:38:52,721][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'CPU': 8.0, 'node:127.0.0.1': 1.0, 'memory': 1560789812.0, 'object_store_memory': 780394905.0}
[2024-09-12 10:38:52,723][flwr][INFO] - Initializing global parameters
[2024-09-12 10:38:52,723][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-12 10:38:59,028][flwr][INFO] - Received initial parameters from one random client
[2024-09-12 10:38:59,029][flwr][INFO] - Evaluating initial parameters
[2024-09-12 10:38:59,092][flwr][INFO] - initial parameters (loss, other metrics): 26.571780268351237, {'accuracy': 0.43833333333333335}
[2024-09-12 10:38:59,096][flwr][INFO] - FL starting
[2024-09-12 10:38:59,097][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-12 10:38:59,151][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=16672, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 39, in fit
    optimizer = config["optimizer"]
                ~~~~~~^^^^^^^^^^^^^
KeyError: 'optimizer'
[2024-09-12 10:39:05,316][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8868, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 39, in fit
    optimizer = config["optimizer"]
                ~~~~~~^^^^^^^^^^^^^
KeyError: 'optimizer'
[2024-09-12 10:39:05,321][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
[2024-09-12 10:39:05,377][flwr][INFO] - fit progress: (1, 26.571780268351237, {'accuracy': 0.43833333333333335}, 6.279547699999966)
[2024-09-12 10:39:05,380][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 2)
[2024-09-12 10:39:24,580][flwr][DEBUG] - evaluate_round 1 received 2 results and 0 failures
[2024-09-12 10:39:24,582][flwr][DEBUG] - fit_round 2: strategy sampled 2 clients (out of 2)
[2024-09-12 10:39:24,634][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=16672, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 39, in fit
    optimizer = config["optimizer"]
                ~~~~~~^^^^^^^^^^^^^
KeyError: 'optimizer'
[2024-09-12 10:39:24,636][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8868, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 39, in fit
    optimizer = config["optimizer"]
                ~~~~~~^^^^^^^^^^^^^
KeyError: 'optimizer'
[2024-09-12 10:39:24,650][flwr][DEBUG] - fit_round 2 received 0 results and 2 failures
[2024-09-12 10:39:24,726][flwr][INFO] - fit progress: (2, 26.571780268351237, {'accuracy': 0.43833333333333335}, 25.62883769999962)
[2024-09-12 10:39:24,729][flwr][DEBUG] - evaluate_round 2: strategy sampled 2 clients (out of 2)
[2024-09-12 10:39:42,896][flwr][DEBUG] - evaluate_round 2 received 2 results and 0 failures
[2024-09-12 10:39:42,898][flwr][DEBUG] - fit_round 3: strategy sampled 2 clients (out of 2)
[2024-09-12 10:39:42,958][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8868, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 39, in fit
    optimizer = config["optimizer"]
                ~~~~~~^^^^^^^^^^^^^
KeyError: 'optimizer'
[2024-09-12 10:39:42,967][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=16672, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 39, in fit
    optimizer = config["optimizer"]
                ~~~~~~^^^^^^^^^^^^^
KeyError: 'optimizer'
[2024-09-12 10:39:42,974][flwr][DEBUG] - fit_round 3 received 0 results and 2 failures
[2024-09-12 10:39:43,049][flwr][INFO] - fit progress: (3, 26.571780268351237, {'accuracy': 0.43833333333333335}, 43.95211379999955)
[2024-09-12 10:39:43,052][flwr][DEBUG] - evaluate_round 3: strategy sampled 2 clients (out of 2)
[2024-09-12 10:40:00,406][flwr][DEBUG] - evaluate_round 3 received 2 results and 0 failures
[2024-09-12 10:40:00,407][flwr][DEBUG] - fit_round 4: strategy sampled 2 clients (out of 2)
[2024-09-12 10:40:00,456][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=16672, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 39, in fit
KeyError: 'optimizer'
[2024-09-12 10:40:00,459][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8868, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 39, in fit
KeyError: 'optimizer'
[2024-09-12 10:40:00,470][flwr][DEBUG] - fit_round 4 received 0 results and 2 failures
[2024-09-12 10:40:00,541][flwr][INFO] - fit progress: (4, 26.571780268351237, {'accuracy': 0.43833333333333335}, 61.44393749999972)
[2024-09-12 10:40:00,543][flwr][DEBUG] - evaluate_round 4: strategy sampled 2 clients (out of 2)
