[2024-09-19 14:26:01,230][numexpr.utils][INFO] - NumExpr defaulting to 8 threads.
[2024-09-19 14:26:04,638][flwr][WARNING] - Both server and strategy were provided, ignoring strategy
[2024-09-19 14:26:04,639][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-19 14:26:14,921][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'memory': 683343054.0, 'node:127.0.0.1': 1.0, 'CPU': 8.0, 'object_store_memory': 341671526.0}
[2024-09-19 14:26:14,922][flwr][INFO] - Initializing global parameters
[2024-09-19 14:26:14,922][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-19 14:26:17,993][flwr][INFO] - Received initial parameters from one random client
[2024-09-19 14:26:17,995][flwr][INFO] - Evaluating initial parameters
[2024-09-19 14:26:18,074][flwr][INFO] - initial parameters (loss, other metrics): 20.622667821248374, {'global accuracy': 0.5616666666666666}
[2024-09-19 14:26:18,074][flwr][INFO] - FL starting
[2024-09-19 14:26:18,076][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-19 14:26:18,110][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=6688, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\VscodeProjects\Tesi-Francesco\clients\client_scaffold.py", line 54, in fit
    if os.path.exists(f"{self.dir}/client_cv_{self.cid}.pt"):
                                              ^^^^^^^^
AttributeError: 'ScaffoldFlowerClient' object has no attribute 'cid'
[2024-09-19 14:26:21,212][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=11276, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\VscodeProjects\Tesi-Francesco\clients\client_scaffold.py", line 54, in fit
    if os.path.exists(f"{self.dir}/client_cv_{self.cid}.pt"):
                                              ^^^^^^^^
AttributeError: 'ScaffoldFlowerClient' object has no attribute 'cid'
[2024-09-19 14:26:21,216][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
